### ISSUE TITLE
List selection problems on Android

### ISSUE THREAD

**Issue by mwarnett** [codenameone/CodenameOne#1645]
My app has a list with a custom renderer which has always worked fine. The renderer does set fg and bg colors based on selection.

Building for Android from the latest code has broken list selection. Selecting one list entry changes the background color on all list entries. Scrolling the list causes the background color to change as the list scrolls.

I have included sample code to reproduce the problem.

The fix you published in the forums does resolve this issue. I added Display.getInstance().setProperty("platformHint.compatPaintMode", "true"); and I can now select entries in my list and scroll without problems. So I have a workaround.

To use the sample code run the app to display the list. Touch one row to select it, the background color on all cells change. Try scrolling the list.

package com.readerware.xware.test;

import com.codename1.components.InfiniteProgress;
import com.codename1.io.Log;
import com.codename1.ui.Button;
import com.codename1.ui.Command;
import com.codename1.ui.Component;
import com.codename1.ui.Container;
import com.codename1.ui.Dialog;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Label;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.List;
import com.codename1.ui.layouts.GridBagConstraints;
import com.codename1.ui.layouts.GridBagLayout;
import com.codename1.ui.layouts.Insets;
import com.codename1.ui.list.DefaultListModel;
import com.codename1.ui.list.ListModel;
import com.codename1.ui.plaf.Style;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.TextArea;
import com.codename1.ui.TextField;
import com.codename1.ui.Toolbar;
import com.codename1.ui.animations.CommonTransitions;
import com.codename1.ui.geom.Dimension;
import com.codename1.ui.layouts.FlowLayout;
import com.codename1.ui.layouts.LayeredLayout;
import com.codename1.ui.list.ListCellRenderer;
import com.codename1.ui.util.Resources;
import java.io.IOException;

public class TWMain {

    private Form current;
    private Form form;
    protected Toolbar _myToolbar;

    public void init(Object context) {

        try {
            Resources theme = Resources.openLayered("/theme");
            UIManager.getInstance().setThemeProps(theme.getTheme(theme.getThemeResourceNames()[0]));
        } catch(IOException e){
            e.printStackTrace();
        }
        // Pro users - uncomment this code to get crash reports sent to you automatically
        Display.getInstance().addEdtErrorHandler(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                evt.consume();
                Log.p("Exception in AppName version " + Display.getInstance().getProperty("AppVersion", "Unknown"));
                Log.p("OS " + Display.getInstance().getPlatformName());
                Log.p("Error " + evt.getSource());
                Log.p("Current Form " + Display.getInstance().getCurrent().getName());
                Log.e((Throwable)evt.getSource());
                Log.sendLog();
            }
        });
    }

    public void start() {
        if(current != null){
            current.show();
            return;
        }

        form = new MyForm();

        form.show();
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
    }

    public void destroy() {
    }

    private class MyForm    extends     Form
                            implements  ActionListener {
        public MyForm() {
            super("CodenameOne Test");
            getContentPane().setLayout(new BorderLayout());

            setTintColor(0x80808080);

            Command backCommand = new Command("Home", 1);
            setBackCommand(backCommand);

            _myToolbar = new Toolbar();
            setToolBar(_myToolbar);
            _myToolbar.setTitle("My Test App");

            Command command1 = new Command("Menu 1", 2);
            _myToolbar.addCommandToOverflowMenu(command1);

            Command command2 = new Command("Menu 2", 3);
            _myToolbar.addCommandToOverflowMenu(command2);

            Command command3 = new Command("Menu 3", 4);
            _myToolbar.addCommandToOverflowMenu(command3);

            Command command4 = new Command("Menu 4", 5);
            _myToolbar.addCommandToOverflowMenu(command4);

            Command command5 = new Command("Menu 5", 6);
            _myToolbar.addCommandToOverflowMenu(command5);

            addCommandListener(this);

            setLayout(new BorderLayout());
            setScrollable(false);

            ListModel listModel = new DefaultListModel();

            for (int i=0; i<100; i++) {
                listModel.addItem("Line " + (i + 1));
            }

            List list = new List();
            list.setScrollVisible(false);
            list.setRenderer(new MyListCellRenderer());
            list.setMutableRendererBackgrounds(false);
            list.setModel(listModel);

            listModel.setSelectedIndex(-1);
            addComponent(BorderLayout.CENTER, list);
        }

        public void actionPerformed(ActionEvent actionEvent) {
            Command command = actionEvent.getCommand();

            if (command != null) {
                int cmd = command.getId();

                switch (cmd) {
                  case 1:
                    stop();
                    Display.getInstance().exitApplication();
                    return;

                  case 2:
                    break;

                  default:
                    break;
                }
            }
        }
    }

    /**
      * List Cell Renderer for ListResultsForm.
      *
      * @author mcw
      */
    public class MyListCellRenderer extends    Container
                                    implements ListCellRenderer {
        /*
         * List cell renderer
         */
        private Container               _container;
        private Label                   _cover;
        private TextArea                _item;

        /**
          * Default constructor.
          *
          */
        public MyListCellRenderer() {
            super(new LayeredLayout());

            setCellRenderer(true);

            _container = new Container(new BorderLayout());

            _cover = new Label();
            Style coverStyle = _cover.getStyle();
            coverStyle.setMargin(Component.RIGHT, (coverStyle.getMargin(Component.RIGHT) * 2));

            _item = new TextArea();
            _item.setUIID("Label");
            _item.setEditable(false);
            _item.setRows(3);
            _item.setGrowByContent(false);

            _container.addComponent(BorderLayout.WEST, _cover);
            _container.addComponent(BorderLayout.CENTER, _item);

            addComponent(_container);
        }

        /**
          * List cell renderer. Displays cover image and basic info in a formatted
          * string.
          *
          * @param  list
          * @param  value
          * @param  index
          * @param  isSelected
          * @return cellRenderer                    Cell Renderer component
          */
        public Component getListCellRendererComponent(List list,
                                                      Object value,
                                                      int index,
                                                      boolean isSelected) {
            if (value == null) {
                return this;
            }

            _item.setText((String) value);

            Style itemStyle = _item.getStyle();
            Style coverStyle = _cover.getStyle();
            Style containerStyle = _container.getStyle();

            itemStyle.setBgTransparency(255);
            coverStyle.setBgTransparency(255);
            containerStyle.setBgTransparency(255);

            if (isSelected == true) {
                itemStyle.setFgColor(0xff0000);
                itemStyle.setBgColor(0x000000);
                coverStyle.setBgColor(0xff0000);
                containerStyle.setBgColor(0x000000);
            }
            else {
                itemStyle.setFgColor(0x000000);
                itemStyle.setBgColor(0xffffff);
                coverStyle.setBgColor(0x000000);
                containerStyle.setBgColor(0xffffff);
            }

            return this;
        }

        public Component getListFocusComponent(List list) {
            return null;
        }
    }
}

**Comment by codenameone** [comment]
Try calling `setRenderer(true)` on all the elements. 

I think this might relate to the different style objects being returned for every entry. To see if this is the case try doing the set colors both on the selected and unselected styles.

**Comment by mwarnett** [comment]
I tried adding setCellRenderer(true) to all components. It does not make a difference but I left it in.

I don't really understand what it is you are asking me to do with the styles. My understanding of setSelectedStyle is that if the component is in a selected state, then it would use that style. But not all the components I use in my renderer have a selected state. That is why I use setStyle(), I check the state passed to the renderer and set the component style accordingly. That has always worked on both Android and iOS until now.

I played around with using the selected, pressed and unselected styles but the selection was never shown, not even on the item as I touched it.

**Comment by codenameone** [comment]
Try changing this as:

```java
        itemStyle.setFocus(true);
        coverStyle.setFocus(true);
        containerStyle.setFocus(true);
        Style itemStyle = _item.getStyle();
        Style coverStyle = _cover.getStyle();
        Style containerStyle = _container.getStyle();
```

**Comment by mwarnett** [comment]
Setting the focus on the component prior to calling getStyle made no difference, all list items are still selected when you select one.

**Comment by codenameone** [comment]
I'll try to reproduce this.

**Comment by codenameone** [comment]
Thanks this is fixed in git and in the servers soon. Reviewing it for 3.3 inclusion since its pretty critical.

**Comment by Manukaki** [comment]
I just send an Android compile, this issue still exist. Are we at version 3.3 right now?

**Comment by Manukaki** [comment]
mwarnett, should I update here, since this ticket already close?

**Comment by mwarnett** [comment]
Yes this problem still exists in current builds.

I was working around this problem, using Display.getInstance().setProperty("platformHint.compatPaintMode", "true"); and that does fix it. I had forgotten to take this out, with this statement removed the original list selection problems I reported still exist.

**Comment by codenameone** [comment]
This was a bit of a tough one. Notice that in order to use the renderer above in the new pipeline you will have to declare the individual components within the renderer as renderers by adding this to the bottom of the constructor:

````java
                _container.setCellRenderer(true);
                _cover.setCellRenderer(true);
                _item.setCellRenderer(true);
````

We will switch to the new pipeline after the release of 3.4 so I suggest adapting the code ASAP.
