### ISSUE TITLE
clipping failure on Android

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#1875]
I noticed that in some circumstances, images are displayed outside their proper
bounds.   I'm still looking for a good test case for my original problem, but I 
stumbled into this.  The attached program ought to produce a blank olive
window, with a blue rectangle in the upper left quadrant, and a scattering
of white rectangles in a random pattern.  Any drawing outside the blue rectangle, other than
the white rectangles, is an error.

''''java
package dtest.boardspace;
//
// this version shows overlay "graying" bug seen only on kindle fire
//

import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.ui.Graphics;
import com.codename1.ui.layouts.BorderLayout;

import java.util.Random;
import java.util.Vector;

public class Dtest  {

```
Random r = new Random(12345);


private Form current;
@SuppressWarnings("unused")
private Resources theme;
 int step = 0;
public void init(Object context) {
    theme = UIManager.initFirstTheme("/theme");
     // Pro only feature, uncomment if you have a pro subscription
    // Log.bindCrashProtection(true);
}

public void start() {
    if(current != null){
        current.show();
        return;
    }
    Form hi = new Form("Hi >>0 World");
     current = hi;
    hi.setLayout(new BorderLayout());
    hi.addComponent(BorderLayout.CENTER, new Label("Hi Overlay World 2") {
        public void drawRandom(Graphics g,Random r,int w,int h,int chipw,int chiph,int depth)
        {
            int rx = r.nextInt(w*3)-w;
            int ry = r.nextInt(h*3)-h;
            int cx = r.nextInt(w*3)-w;
            int cy = r.nextInt(h*3)-h;
            int clip[] = g.getClip();
            step++;
            g.clipRect(cx,cy,chipw,chiph);
            int []clip2 = g.getClip();
            g.setColor(0xff00+step);
            g.fillRect(rx,ry,chipw,chiph);
            g.setColor(0xffffff);
            g.drawString(""+step,rx+chipw/2,ry+chiph/2);
            if(depth>0) { drawRandom(g,r,w,h,chipw,chiph,depth-1); }
            g.setClip(0,0,w,h);
            g.drawRect(rx, ry, chipw, chiph);
            g.drawString(""+step,rx+chipw/2,ry+chiph/2);
            System.out.println("step "+step+" "+cx+","+cy+" to "+clip2[0]+","+clip2[1]+" "+clip2[2]+"x"+clip2[3]);
            g.setClip(clip);
        }
        @Override
        public void paint(Graphics g) {
            int w = getWidth();
            int h = getHeight();
            String message = "";
            Vector<String>messages = new Vector<String>();
            int chipw = 200;
            int chiph = 40;

            g.setColor(0x8f8f9f7f);
            g.fillRect(0,0,w,h);
            g.clipRect(150,150,chipw+100,chiph+100);    // clip to a small rectangle
            g.setColor(0x245678);
            g.fillRect(0, 0, w, h);


            for(int i=0;i<100;i++)
            {
                drawRandom(g,r,w,h,chipw,chiph,2);
                g.setColor(0xff00+i);
                g.drawLine(150, 150, w, 150+i*4);
            }
            g.setColor(0xffffff);
            g.drawLine(0,0,w,h);
            /*
            for(int i=10;i<w;i+=40)
            {
            int old[] = g.getClip();
                {   // partially or fully visible
                    g.clipRect(200+i,200,chipw,chiph);
                    message += "clipRect "+200+i+" "+200+" "+chipw+" "+chiph+" to "+" ";
                    int rr[] = g.getClip();
                    g.setClip(rr);
                    int rr2[] = g.getClip();
                    message += (rr==null) ? "null" : ""+rr[0]+" "+rr[1]+" "+rr[2]+" "+rr[3]+" / ";
                    message += (rr2==null) ? "null" : ""+rr2[0]+" "+rr2[1]+" "+rr2[2]+" "+rr2[3];
                    messages.addElement(message);
                    message = "";



                    g.drawImage(chip,200+i,200);
                }


            g.setClip(old);
            }
            g.setClip(0,0,w,h);
            for(int i=0;i<messages.size();i++)
            {   
            g.drawString(messages.elementAt(i),10,10+30*i);
            }

                            */


         }

    });
    hi.show();

}

public void stop() {
    current = Display.getInstance().getCurrent();
}

public void destroy() {
}
```

}
''''
On my android devices, it produces a scattering of non-empty white rectangles.
Curiously, it does this ONLY on the initial launch of the program.  Every time you
swipe the screen of your device, a repaint will be triggered and a new pattern
will be produced.  After the first time, everything is correct.

**Comment by ddyer0** [comment]
also, this works as expected in the simulator and on IOS

**Comment by ddyer0** [comment]
Here's another variant that doesn't depend on randomness.  As with the original, all non-white
drawing outside the blue rectangle is an error.  As with the original, the problem only occurs on
the first refresh of the window.
''''java
package dtest.boardspace;
//
// this version shows overlay "graying" bug seen only on kindle fire
//

import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Image;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.ui.Graphics;
import com.codename1.ui.layouts.BorderLayout;

import java.util.Random;
import java.util.Vector;


public class Dtest  {
	

 
    private Form current;
    @SuppressWarnings("unused")
	private Resources theme;
     int step = 0;
    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");
         // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }
   
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        Form hi = new Form("Hi >>0 World");
         current = hi;
        hi.setLayout(new BorderLayout());
        hi.addComponent(BorderLayout.CENTER, new Label("Hi Overlay World 2") {
 
        	@Override
            public void paint(Graphics g) {
             	int w = getWidth();
            	int h = getHeight();
            	Random r = new Random(12345);
            	String message = "";
            	Vector<String>messages = new Vector<String>();
            	int chipw = 500;
            	int chiph = 400;

            	g.setColor(0x8f8f9f7f);
            	g.fillRect(0,0,w,h);
            	g.clipRect(150,150,chipw+100,chiph+100);	// clip to a small rectangle
            	g.setColor(0x245678);
            	g.fillRect(0, 0, w, h);
            	
            	for(int i=0;i<100;i++)
            	{	g.setColor(0xff00+i);
            	    int clip[]=g.getClip();
            	    int x = 150+chipw-50+i*5;
            	    int y = 150+i*5;
            	    g.clipRect(x+1, y+1, 18,18);
            	    g.setColor(0xff00+i*5);
            		g.fillRect(x,y,20,20);
            		g.setClip(0,0,w,h);
            		g.setColor(0xffffff);
            		g.drawRect(x, y-40, 20, 20);
            		g.setClip(clip);
            	}
            	
            	/*
            	for(int i=10;i<w;i+=40)
            	{
            	int old[] = g.getClip();
             		{ 	// partially or fully visible
            			g.clipRect(200+i,200,chipw,chiph);
            			message += "clipRect "+200+i+" "+200+" "+chipw+" "+chiph+" to "+" ";
            			int rr[] = g.getClip();
            			g.setClip(rr);
            			int rr2[] = g.getClip();
            			message += (rr==null) ? "null" : ""+rr[0]+" "+rr[1]+" "+rr[2]+" "+rr[3]+" / ";
               			message += (rr2==null) ? "null" : ""+rr2[0]+" "+rr2[1]+" "+rr2[2]+" "+rr2[3];
               			messages.addElement(message);
            			message = "";
            			
            			
            			
            			g.drawImage(chip,200+i,200);
            		}
 
             	
               	g.setClip(old);
            	}
            	g.setClip(0,0,w,h);
            	for(int i=0;i<messages.size();i++)
            	{	
            	g.drawString(messages.elementAt(i),10,10+30*i);
            	}
            	
            	               	*/

            	
             }
            
        });
        hi.show();
        
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
    }
    
    public void destroy() {
    }
    



}
''''

**Comment by codenameone** [comment]
Can you provide screenshots of what you are seeing in the simulator/android and the same for the other issue you filed with iOS. I see some nuanced usage here that looks suspicious but it's hard to see what is going on.

FYI You tried to do code highlighting but you used the ' character instead of the backtick which is admittedly a very confusing choice of characters but that's markup... In a Mac it's the key right nex to the left shift. On Windows see: http://superuser.com/questions/254076/how-do-i-type-the-tick-and-backtick-characters-on-windows

**Comment by ddyer0** [comment]
This is the original "random rectangles" as seen on the simulator.  Picture is correctly rendered.
![android-rectangles-simulator](https://cloud.githubusercontent.com/assets/5963076/18137749/93667b98-6f5e-11e6-9387-b591d730437a.jpg)

**Comment by ddyer0** [comment]
Here's an android screen shot.  All the filled and partially filled rectangles outside the big blue one
are errors.
![screenshot_2016-08-31-09-45-47](https://cloud.githubusercontent.com/assets/5963076/18138335/12300dd4-6f61-11e6-913b-35c296bdadbe.png)

**Comment by shannah** [comment]
I tried out your [non-randomized test case](https://github.com/codenameone/CodenameOne/issues/1875#issuecomment-243637192) and it worked properly on Android and Simulator.  Looks like this issue was already fixed.  If you have another test case that fails, pass it along and I'll reopen.

**Comment by ddyer0** [comment]
It still fails for me.  Here's a screen shot made from fresh build just now.  All the green stuff outside the
box is incorrect.
![screenshot_2017-03-22-15-25-36](https://cloud.githubusercontent.com/assets/5963076/24223974/03d4183e-0f16-11e7-8b8b-cdeb19ae3a34.png)

**Comment by shannah** [comment]
Is that the exact same test case you posted?  My Nexus 5 runs it fine.    What device/android version  are you running on?

**Comment by shannah** [comment]
@ddyer0 Can you check to see if this is still happening for you.  I haven't been able to reproduce it still but made a change (listed above), that should be on the build server by now that might have an effect.

**Comment by ddyer0** [comment]
the nonrandom test looks ok now.

**Comment by shannah** [comment]
Great.  I'm going to close this issue then.
