### ISSUE TITLE
New GUI Builder Button Action Event Not Working

### ISSUE THREAD

**Issue by tobymundy** [codenameone/CodenameOne#1927]
I updated the CodenameOne plugin on Netbeans today I ran a 'new GUI builder' created app that had previously been working. I found that none of the buttons were working. I examined the "Generated Code" section and found that the 'EventCallbackClass' 'actionPerformed' has nothing in the if(sourceComponent == gui_Button_1) body. The GUI builder is generating the actionEvent="true" xml code correctly. I created a new simple app and found the same issue. See code below:

xml file with actionEvent="true" generated OK
`<component type="Button" text="Button" name="Button_1" actionEvent="true">`

From "Generated Code" section, class EventCallbackClass, actionPerformed
`if(sourceComponent == gui_Button_1) { // THE BODY OF THIS IF STATEMENT IS EMPTY
                }`

The if statement should contain `onButton_1ActionEvent(ev)`

**Comment by codenameone** [comment]
This was fixed earlier in the week, we'll release a plugin update today that should address this.
Thanks.

**Comment by tobymundy** [comment]
I updated to the latest 3.5.6 version of the Codename One plugin but am still experiencing the same issue. I'm not sure that this issue should be closed.

**Comment by codenameone** [comment]
Go to project properties. Click "OK". Then try running again.
