### ISSUE TITLE
[BUG] Codename One Designer resets CornerRadius to zero 

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2338]
I have the following code in theme.xml:

<border key="LoginButton.border" type="roundRect" strokeColor="255" strokeOpacity="255" strokeThickness="0.2" strokeMM="true" shadowSpread="0.0" shadowOpacity="0" shadowX="0.0" shadowY="0.0" shadowBlur="1.0" topOnlyMode="false" bottomOnlyMode="false" **_CornerRadius="3.0"_** bezierCorners="true" />

Every time that I open the theme.res with the Codename One Designer, the value CornerRadius is reset to zero, in this way:

<border key="LoginButton.border" type="roundRect" strokeColor="255" strokeOpacity="255" strokeThickness="0.2" strokeMM="true" shadowSpread="0.0" shadowOpacity="0" shadowX="0.0" shadowY="0.0" shadowBlur="1.0" topOnlyMode="false" bottomOnlyMode="false" **_CornerRadius="0.0"_** bezierCorners="true" />

It's very annoying.

**Comment by jsfan3** [comment]
Tested on Windows 8.
To reproduce the bug, start a new project and create a style with a round rect border with a radious that is not zero. Save the theme, close the  Codename One Designer and reopen it.

**Comment by codenameone** [comment]
This was already fixed in git a while back. It should be fixed in the update tomorrow.

**Comment by jsfan3** [comment]
Today I installed the update of Codename One to Version: 3.8.3
The bug still exists.

**Comment by codenameone** [comment]
The designer will no longer update with the plugin update as it did in older versions. Try using Update Client Libs and make sure it actually updated https://www.codenameone.com/blog/new-update-framework.html

**Comment by jsfan3** [comment]
I cannot do the update: [https://github.com/codenameone/CodenameOne/issues/2341](https://github.com/codenameone/CodenameOne/issues/2341)

**Comment by jsfan3** [comment]
Ok, I've done the update and the bug still exists. Can you please reopen this issue? Thanks

**Comment by jsfan3** [comment]
I confirm that your last update to solve the bug https://github.com/codenameone/CodenameOne/issues/2342 solved also this issue.
