### ISSUE TITLE
TextArea and sidemenu issue in codenameone

### ISSUE THREAD

**Issue by bbeckk** [codenameone/CodenameOne#2444]
I've a couple of textFields and textAreas in a screen. When any one of them is focused and then if the sidemenu is opened, I can write on top of side menu. The keyboard doesn't disappear when sidemenu is clicked. In other cases as well, when keyboard is opened and the components like Label etc are touched, it'd be nicer if the keyboard disappear automatically.

See the video [here](https://youtu.be/vIzYJo6kb4Y)

**Comment by shannah** [comment]
This was fixed yesterday and will be included in the update today.
https://github.com/codenameone/CodenameOne/commit/3cc07a81f57c684d8c6c722ae7b3db12dd8839d1

**Comment by bbeckk** [comment]
The issue still exists in my project. It is seen in the simulator as well. I've updated the cn1 lib. to 4.0.0

**Comment by codenameone** [comment]
Does that happen with swipe in of the side menu?

**Comment by bbeckk** [comment]
No swipe can not be done with keyboard on. I think it is solved in android but in iOS the problem still is there. It doesn't happen all the time in iOS but if you focus on text inputs and keyboard is on, then when you scroll the component below the keyboard and open the sidemenu the issue appears in iOS. Sometimes the components appear below the keyboard initially. I have tested it in iOS 6 plus

See the video [here](https://youtu.be/NLtI0TTzWms)
