### ISSUE TITLE
Codename One plugin version is 0.0 instead of 5.0

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2547]
After a week away, here I am :)

Netbeans 9 doesn't allow to update to Codename One plugin 5.0 using the "check updates" feature. I use the NetBeans Plugin Update Center, as described here:
https://www.codenameone.com/blog/netbeans-plugin-update-center.html

The only way I found to install the last plugin is to remove the plugin 4.4 and then install manually this file:
https://www.codenameone.com/files/netbeans/com-codename1.nbm

BUT... it reports that the version is 0.0, as in this screenshot:
![version](https://user-images.githubusercontent.com/1997316/45600654-89d4ef80-ba00-11e8-8a97-77416bd3520e.png)

Note that I'm sure that the installed 0.0 is actually the 5.0 because the default project is a bare bones project with a native theme (with it wasn't so in the previous versions of Codename One).

After this update, Netbeans suggests me to update from 0.0 to 4.4...

Please do a check,
thank you

**Comment by codenameone** [comment]
Thanks this is fixed but will take some time to propagate

**Comment by jsfan3** [comment]
After three days the problem is not solved. Netbeans 9 continues to propose to install the Codename One plugin Version: 4.4.0 of 17/08/18.
I manually downloaded again the 5.0 plugin and it's versioned as 0.0

**Comment by codenameone** [comment]
It's still pending verification. NetBeans has the absolute worse plugin submission policy.
I suggest switching to our update center which is reliably updated. See https://www.codenameone.com/blog/netbeans-plugin-update-center.html

**Comment by jsfan3** [comment]
I'm sorry, but your suggested solution (using the Codename One update center) doesn't work.

In this video I show you exactly what I see:
https://www.informatica-libera.net/videoLavoro/netbeans9.mp4

**Comment by codenameone** [comment]
If you installed the plugin originally from NetBeans center it will keep looking there. You can safely uninstall and reinstall from our center and you won't lose your settings.

**Comment by jsfan3** [comment]
I uninstalled the plugin, I enabled the "Codename One Update Center" and I disabled the default "Plugin Portal": it enabled me to install the version "0.0"... so the version 5.0 seems to be versioned 0.0 in your update center... or, at least, Netbeans 9 sees it so.

**Comment by codenameone** [comment]
That's weird it's 5.0 for me and I don't think 9 should impact that. @shannah can you reproduce this?
<img width="1003" alt="screen shot 2018-09-22 at 8 39 04" src="https://user-images.githubusercontent.com/2353641/45913818-1c332400-be43-11e8-8c0e-1541adba5a0c.png">

**Comment by jsfan3** [comment]
I can add another info: I've just experienced the same issue with another computer with Netbeans 8.2 and Java 1.8.

**Comment by codenameone** [comment]
Try now, it was finally approved.

**Comment by jsfan3** [comment]
Good news: after reading your comment, on Netbeans 8.2 I've just updated to your plugin to the 5.0 version, so the problem seems solved... tomorrow I will be able to check if I can update to 5.0 also on Netbeans 9.

**Comment by jsfan3** [comment]
I confirm that the problem is solved also in Netbeans 9.
