### ISSUE TITLE
Getting safe area x = 0 y = 132 size = width = 1125 height = 2202

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#3024]
Every time that I tap on a tab, I get in the log something like:
```
Getting safe area x = 0 y = 132 size = width = 1125 height = 2202
```

I suppose that this should be hidden.

**Comment by shannah** [comment]
This was fixed as a part of https://github.com/codenameone/CodenameOne/commit/9fc2b4bd89eb3e2fcc932d18404236e94bdf6f53

**Comment by jsfan3** [comment]
After your answer, I updated my local clone of the CN1 sources (to compile against that), but this issue still happen.
