### ISSUE TITLE
Build server JavaAPI still not updated to support AppleLogin

### ISSUE THREAD

**Issue by javieranton-zz** [codenameone/CodenameOne#3082]
[Following this](https://github.com/codenameone/CodenameOne/issues/3068)
@codenameone @shannah 
Same old error still being thrown by build server

`com_codename1_social_AppleLogin.m:22:10: fatal error: 'java_io_StringReader.h' file not found
#include "java_io_StringReader.h"
`

Seems server's JavaAPI wasn't updated?

**Comment by javieranton-zz** [comment]
So I downloaded the cn1lib and found the following:
1- It wouldn't compile with the available CodenameOne jar because it was missing `com.codename1.util.AsyncResource;`. However, that was an unused import. I did link the lib to the latest CodenameOne source which apparently does sinclude this resource, and that took care of it. So it seems that the default CodenameOne jar and the solution on GitHub are a bit different
2- The library still wouldn't compile because it can't find the symbol `java.io.StringReader`. I linked the library to the latest JavaSE port from the repository to make sure it wasn't missing anything in case the default JavaSE is still old. It still threw this error
I am not an expert but my guess is that you are using a different JavaSE. It's not just different from the one running on the server, it's also different from the one we get when we start projects in IDEs and from the one under Ports/JavaSE.
3- After this the only missing piece was to manually reference WebView.jar in my app's project, not sure why this was necessary as the build.xml bit should have taken care of this I think, but nevermind

This kind of worked. I followed the very simple example in [here](https://www.codenameone.com/blog/sign-in-with-apple-support.html) and right after calling doLogin I got an error: `java.lang.IllegalStateException: Must set key ID to do Oauth2 with AppleLogin`.

To verify, I ran the demo app and got the same result. After throwing this exception the app crashes

I will be forking this and keeping a local copy in which I use `com.codename1.util.regex.StringReader` for now

**Comment by javieranton-zz** [comment]
I think that the way the blog page was phrased was a bit misleading

> If you only intend to support Apple sign-in with your iOS app, and not on other platforms, then the process is pretty simple - you just check a box next to "Sign-in with Apple" in the capabilites section of your App ID details page

Then, it says

> Set-up for other platforms is a bit more involved. You need to create a "Services ID" (used for the Oauth2 client ID), and generate a private key so you will be able to generate the Oauth2 client secret on-demand.

For full instructions see the setup documentation in the cn1lib’s wiki.

The confusion lies in that when we only want to develop on ios, we can think it's not necessary to read the full instructions as it says after mentioning other platforms. Then we skip generating keys etc which was my problem I think

**Comment by javieranton-zz** [comment]
So the blog entry says

> If you only intend to support Apple sign-in with your iOS app, and not on other platforms, then the process is pretty simple - you just check a box next to "Sign-in with Apple" in the capabilites section of your App ID details page

But looking at the [code](https://github.com/javieranton-zz/cn1-applesignin/blob/57c7800efaf43033d123491dd26a5cc108a5705f/CN1AppleSignIn/native/ios/com_codename1_auth_apple_AppleSignInNativeImpl.m#L148) this is true only for iOS13 

So perhaps the blog entry should mention that a keyId, a privateKey and a teamId are neede to generate the clientSecret when running lower than iOS13?

**Comment by javieranton-zz** [comment]
Another one: getFullName() returns an empty string. In my test case I am using a simple name with normal characters with 1 first name and 1 last name

**Comment by javieranton-zz** [comment]
I managed to publish to production. So far, one user successfully registered and 2 were failed attemps with error: `The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1000`
It also works fine when I try it myself. Done some searching and it seems it might be somehow related to "entitlements", but my knowledge of xcode and ios in general don't really let me progress much to understand/fix this

**Comment by shannah** [comment]
This likely points to a configuration problem with your App ID.  Make sure you added the "Sign in with apple" capability to your app ID before generating your provisioning profile.
https://github.com/shannah/cn1-applesignin/wiki/Getting-Started

**Comment by javieranton-zz** [comment]
@shannah thanks for replying. I laready had that enabled. Do you think I should regenerate certificates and provisioning profiles and submit a new build? Do you think this makes sense with that 1 user and myself are able to run it but 2 other users fail

**Comment by shannah** [comment]
Also, make sure that the `ios.entitlements.applesignin` build hint is true.  If you ran the sign-in in the simulator, it would have automaticlally added this build hint, but if you don't have it on in simulator, it's possible that this step is never run.

**Comment by javieranton-zz** [comment]
Yep checked that too thx. I will submit an update with new provisioning profiles and certificates and get back with results at some point

**Comment by shannah** [comment]
I'm pretty sure this is fixed now, based on other postings of OP.

**Comment by javieranton-zz** [comment]
I've observed a pretty high rate of success (around 75% of logins). The rest still throw either a 1000 or a 1001 error. I am not sure if this is because of Apple, or because the users press something (cancel etc), either way since this is a pretty new feature perhaps I will be able to understand this better in the future. And for now we can add Apple Login which will allow us to continue to publish on App store

**Comment by javieranton-zz** [comment]
Update: I seem to have pinned down the reason why some error messages were being logged. Whenever a user taps on Apple Sign In, and then decides to cancel, a 1001 error is returned in the error callback
