### ISSUE TITLE
CEF doesn't work -> GPU process has crashed

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#3195]
Test case:
```
        Form hi = new Form("Hi World", new BorderLayout());
        Container centerCnt = new Container(BorderLayout.center());
        Container southCnt = new Container(BoxLayout.y());
        Button button = new Button("Test Gallery");
        hi.add(BorderLayout.NORTH, button);
        hi.add(BorderLayout.CENTER, centerCnt);
        hi.add(BorderLayout.SOUTH, southCnt);
        hi.show();
        
        button.addActionListener(l-> {
            CN.openGallery((ActionListener) (ActionEvent evt) -> {
                if (evt == null || evt.getSource() == null) {
                    centerCnt.removeAll();
                    centerCnt.add("Gallery closed");
                    centerCnt.revalidate();
                }
                String galleryFile = (String) evt.getSource();
                try {
                    southCnt.removeAll();
                    southCnt.add(new Label("File size: " + FileSystemStorage.getInstance().getLength(galleryFile)));
                    centerCnt.removeAll();
                    Media video = MediaManager.createMedia(galleryFile, true);
                    centerCnt.removeAll();
                    centerCnt.add(BorderLayout.CENTER, new MediaPlayer(video));
                    hi.revalidate();
                } catch(IOException err) {
                    Log.e(err);
                } 
            }, CN.GALLERY_VIDEO);
        });
```

The previous test case works fine only with JavaFX. With CEF, it crashes with the following log:
```
Adding CEF to classpath
Retina Scale: 1.0
Gtk-Message: 09:07:39.863: GtkDialog mapped without a transient parent. This is discouraged.
CEF Args: [--disable-gpu, --disable-software-rasterizer, --disable-gpu-compositing, --touch-events=enabled, --enable-media-stream, --device-scale-factor=4, --force-device-scale-factor=4, --autoplay-policy=no-user-gesture-required, --enable-usermedia-screen-capturing]
Using:
JCEF Version = 83.4.0.260
CEF Version = 83.4.0
Chromium Version = 83.0.4103.106
AppHandler.stateHasChanged: INITIALIZING
initialize on Thread[AWT-EventQueue-0,6,main] with library path /home/francesco/.codenameone/cef/lib/linux64
Added scheme search://
Added scheme client://
Added scheme cn1stream://
LaunchProcess: failed to execvp:LaunchProcess: failed to execvp:
/home/francesco/.codenameone/cef/lib/linux64/jcef_helper

/home/francesco/.codenameone/cef/lib/linux64/jcef_helper
[0802/090745.861350:WARNING:gpu_process_host.cc(1217)] The GPU process has crashed 1 time(s)

DevTools listening on ws://127.0.0.1:8088/devtools/browser/64019fcc-2665-4d23-9867-67206f5c8248
AppHandler.stateHasChanged: INITIALIZED
[0802/090745.934078:WARNING:gpu_process_host.cc(1217)] The GPU process has crashed 2 time(s)
[0802/090745.935981:WARNING:gpu_process_host.cc(1217)] The GPU process has crashed 3 time(s)
[0802/090745.936015:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
Java Result: 133
```

Other info:
I develop inside a Linux machine, virtualized inside VirtualBox. It's possible that CEF hasn't access to the GPU, I'm not sure, however I'm working inside a VirtualBox machine from years and JavaFX never had this type of issue.

**Comment by shannah** [comment]
How did you install CEF?  Using the install shell script, or manually?

This line with chmod in the install shell script.
https://github.com/shannah/codenameone-cef/blob/master/install-linux.sh#L42

**Comment by shai-almog** [comment]
That's my bad. I fixed the blog post instructions to include that line.

**Comment by jsfan3** [comment]
@shai-almog The instructions in the blog are still wrong, because, according to your instructions, the file is unpacked in `.codenameone` instead of `.codenameone/cef`

@shannah I don't know what you mean by "automatic installation". The blog just says to download a zip file, unpack it and execute chmod: https://www.codenameone.com/blog/big-changes-jcef.html
However, after running the chmod you indicated, the error message changed, I get a lot of `java.lang.NullPointerException`. I'll copy it to you:

```
ant -f /home/francesco/NetBeansProjects/TestCEF -Dnb.internal.action.name=debug -Ddebug.class=com.codename1.impl.javase.Simulator debug
Generating GUI sources
No GUI Entries available
init:
Deleting: /home/francesco/NetBeansProjects/TestCEF/build/built-jar.properties
deps-jar:
Updating property file: /home/francesco/NetBeansProjects/TestCEF/build/built-jar.properties
Compile is forcing compliance to the supported API's/features for maximum device compatibility. This allows smaller
        code size and wider device support
compile:
Adding CEF to classpath
Retina Scale: 1.0
Gtk-Message: 08:46:53.095: GtkDialog mapped without a transient parent. This is discouraged.
CEF Args: [--disable-gpu, --disable-software-rasterizer, --disable-gpu-compositing, --touch-events=enabled, --enable-media-stream, --device-scale-factor=4, --force-device-scale-factor=4, --autoplay-policy=no-user-gesture-required, --enable-usermedia-screen-capturing]
Using:
JCEF Version = 83.4.0.260
CEF Version = 83.4.0
Chromium Version = 83.0.4103.106
AppHandler.stateHasChanged: INITIALIZING
initialize on Thread[AWT-EventQueue-0,6,main] with library path /home/francesco/.codenameone/cef/lib/linux64
Added scheme search://
Added scheme client://
Added scheme cn1stream://

DevTools listening on ws://127.0.0.1:8088/devtools/browser/57e3aab8-5b95-46ec-9952-91612c73c46f
AppHandler.stateHasChanged: INITIALIZED
Running ready callbacks
Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" Address changed to data:text/html,%3C!doctype%20html%3E%3Chtml%3E%3Chead%3E%3Cstyle%20type%3D'text%2Fcss'%3Edocument%2C%20body%20%7Bpadding%3A0%3Bmargin%3A0%3B%20width%3A100%25%3B%20height%3A%20100%25%7D%20video%2C%20audio%20%7Bmargin%3A0%3B%20padding%3A0%3B%20width%3A100%25%3B%20height%3A%20100%25%7D%3C%2Fstyle%3E%3C%2Fhead%3E%3Cbody%3E%3Cvideo%20id%3D'cn1Media'%20width%3D'640'%20height%3D'480'%20style%3D'width%3A100%25%3Bheight%3A100%25'%20src%3D'https%3A%2F%2Fcn1app%2Fstreams%2F1'%2F%3E%3Cscript%3Ewindow.cn1Media%20%3D%20document.getElementById('cn1Media')%3Bfunction%20callback(data)%7B%20cefQuery(%7Brequest%3A'shouldNavigate%3A'%2BJSON.stringify(data)%2C%20onSuccess%3A%20function(response)%7B%7D%2C%20onFailure%3Afunction(error_code%2C%20error_message)%20%7B%20console.log(error_message)%7D%7D)%3B%7Dcn1Media.addEventListener('pause'%2C%20function()%7B%20callback(%7B'state'%3A'paused'%7D)%7D)%3Bcn1Media.addEventListener('play'%2C%20function()%7B%20callback(%7B'state'%3A'playing'%7D)%7D)%3Bcn1Media.addEventListener('ended'%2C%20function()%7B%20callback(%7B'state'%3A'ended'%7D)%7D)%3Bcn1Media.addEventListener('durationchange'%2C%20function()%7B%20callback(%7B'duration'%3A%20Math.floor(cn1Media.duration%20*%201000)%7D)%7D)%3Bcn1Media.addEventListener('timeupdate'%2C%20function()%7B%20callback(%7B'time'%3A%20Math.floor(cn1Media.currentTime%20*%201000)%7D)%7D)%3Bcn1Media.addEventListener('volumechange'%2C%20function()%7B%20callback(%7B'volume'%3A%20Math.round(cn1Media.volume%20*%20100)%7D)%7D)%3Bcn1Media.addEventListener('error'%2C%20function()%7B%20var%20msg%20%3D%20'Unknown%20Error'%3B%20try%20%7Bmsg%20%3D%20cn1Media.error.message%20%2B%20'.%20Code%3D'%2Bcn1Media.error.code%3B%7Dcatch(e)%7B%7D%20callback(%7B'error'%3A%20msg%7D)%7D)%3B%3C%2Fscript%3E%20%3C%2Fbody%3E%3C%2Fhtml%3E
Stream was closed
Exception in thread "Thread-571" java.lang.NullPointerException
Stream was closed
	at com.codename1.impl.javase.cef.ResourceHandler.getResponseHeaders(ResourceHandler.java:39)
Exception in thread "Thread-585" java.lang.NullPointerException
	at com.codename1.impl.javase.cef.ResourceHandler.getResponseHeaders(ResourceHandler.java:39)
Stream was closed
Stream was closed
Exception in thread "Thread-601" java.lang.NullPointerException
	at com.codename1.impl.javase.cef.ResourceHandler.getResponseHeaders(ResourceHandler.java:39)
Exception in thread "Thread-617" java.lang.NullPointerException
	at com.codename1.impl.javase.cef.ResourceHandler.getResponseHeaders(ResourceHandler.java:39)
Stream was closed
Exception in thread "Thread-632" java.lang.NullPointerException
	at com.codename1.impl.javase.cef.ResourceHandler.getResponseHeaders(ResourceHandler.java:39)
Stream was closed
Stream was closed
Exception in thread "Thread-648" java.lang.NullPointerException
	at com.codename1.impl.javase.cef.ResourceHandler.getResponseHeaders(ResourceHandler.java:39)
Stream was closed
Exception in thread "Thread-664" java.lang.NullPointerException
	at com.codename1.impl.javase.cef.ResourceHandler.getResponseHeaders(ResourceHandler.java:39)
Exception in thread "Thread-681" java.lang.NullPointerException
	at com.codename1.impl.javase.cef.ResourceHandler.getResponseHeaders(ResourceHandler.java:39)
Stream was closed
Exception in thread "Thread-698" java.lang.NullPointerException
	at com.codename1.impl.javase.cef.ResourceHandler.getResponseHeaders(ResourceHandler.java:39)
Stream was closed
Exception in thread "Thread-714" java.lang.NullPointerException
Stream was closed
	at com.codename1.impl.javase.cef.ResourceHandler.getResponseHeaders(ResourceHandler.java:39)
Exception in thread "Thread-728" java.lang.NullPointerException
	at com.codename1.impl.javase.cef.ResourceHandler.getResponseHeaders(ResourceHandler.java:39)
Stream was closed
Exception in thread "Thread-750" java.lang.NullPointerException
	at com.codename1.impl.javase.cef.ResourceHandler.getResponseHeaders(ResourceHandler.java:39)
Stream was closed
Exception in thread "Thread-764" java.lang.NullPointerException
	at com.codename1.impl.javase.cef.ResourceHandler.getResponseHeaders(ResourceHandler.java:39)
Stream was closed
Exception in thread "Thread-780" java.lang.NullPointerException
	at com.codename1.impl.javase.cef.ResourceHandler.getResponseHeaders(ResourceHandler.java:39)
Stream was closed
Exception in thread "Thread-795" java.lang.NullPointerException
	at com.codename1.impl.javase.cef.ResourceHandler.getResponseHeaders(ResourceHandler.java:39)
Stream was closed
Exception in thread "Thread-810" java.lang.NullPointerException
	at com.codename1.impl.javase.cef.ResourceHandler.getResponseHeaders(ResourceHandler.java:39)
Stream was closed
Exception in thread "Thread-827" java.lang.NullPointerException
	at com.codename1.impl.javase.cef.ResourceHandler.getResponseHeaders(ResourceHandler.java:39)
Stream was closed
Exception in thread "Thread-842" java.lang.NullPointerException
Stream was closed
	at com.codename1.impl.javase.cef.ResourceHandler.getResponseHeaders(ResourceHandler.java:39)
Exception in thread "Thread-856" java.lang.NullPointerException
	at com.codename1.impl.javase.cef.ResourceHandler.getResponseHeaders(ResourceHandler.java:39)
Stream was closed
Exception in thread "Thread-871" java.lang.NullPointerException
	at com.codename1.impl.javase.cef.ResourceHandler.getResponseHeaders(ResourceHandler.java:39)
Stream was closed
Stream was closed
Exception in thread "Thread-888" java.lang.NullPointerException
	at com.codename1.impl.javase.cef.ResourceHandler.getResponseHeaders(ResourceHandler.java:39)
Stream was closed
Exception in thread "Thread-902" java.lang.NullPointerException
	at com.codename1.impl.javase.cef.ResourceHandler.getResponseHeaders(ResourceHandler.java:39)
Stream was closed
Exception in thread "Thread-917" java.lang.NullPointerException
	at com.codename1.impl.javase.cef.ResourceHandler.getResponseHeaders(ResourceHandler.java:39)
Stream was closed
Exception in thread "Thread-931" java.lang.NullPointerException
	at com.codename1.impl.javase.cef.ResourceHandler.getResponseHeaders(ResourceHandler.java:39)
Stream was closed
Exception in thread "Thread-945" java.lang.NullPointerException
	at com.codename1.impl.javase.cef.ResourceHandler.getResponseHeaders(ResourceHandler.java:39)
Stream was closed
Exception in thread "Thread-961" java.lang.NullPointerException
	at com.codename1.impl.javase.cef.ResourceHandler.getResponseHeaders(ResourceHandler.java:39)
Stream was closed
Exception in thread "Thread-977" java.lang.NullPointerException
	at com.codename1.impl.javase.cef.ResourceHandler.getResponseHeaders(ResourceHandler.java:39)
Stream was closed
Exception in thread "Thread-993" java.lang.NullPointerException
	at com.codename1.impl.javase.cef.ResourceHandler.getResponseHeaders(ResourceHandler.java:39)
Stream was closed
Exception in thread "Thread-1010" java.lang.NullPointerException
	at com.codename1.impl.javase.cef.ResourceHandler.getResponseHeaders(ResourceHandler.java:39)
Stream was closed
Exception in thread "Thread-1025" java.lang.NullPointerException
	at com.codename1.impl.javase.cef.ResourceHandler.getResponseHeaders(ResourceHandler.java:39)
Stream was closed
Exception in thread "Thread-1039" java.lang.NullPointerException
	at com.codename1.impl.javase.cef.ResourceHandler.getResponseHeaders(ResourceHandler.java:39)
[0804/084702.737448:ERROR:batching_media_log.cc(38)] MediaEvent: {"error":"FFmpegDemuxer: data source error"}
[0804/084702.737650:ERROR:batching_media_log.cc(35)] MediaEvent: {"pipeline_error":9}
[EDT] 0:0:12,106 - Codename One revisions: 7dd4e7d08b3442d90959477ee52a5ae8c4361b29

[EDT] 0:0:12,126 - . Code=4
[0804/084707.534444:INFO:CONSOLE(1)] "Uncaught (in promise) NotSupportedError: The element has no supported sources.", source: data:text/html,%3C!doctype%20html%3E%3Chtml%3E%3Chead%3E%3Cstyle%20type%3D'text%2Fcss'%3Edocument%2C%20body%20%7Bpadding%3A0%3Bmargin%3A0%3B%20width%3A100%25%3B%20height%3A%20100%25%7D%20video%2C%20audio%20%7Bmargin%3A0%3B%20padding%3A0%3B%20width%3A100%25%3B%20height%3A%20100%25%7D%3C%2Fstyle%3E%3C%2Fhead%3E%3Cbody%3E%3Cvideo%20id%3D'cn1Media'%20width%3D'640'%20height%3D'480'%20style%3D'width%3A100%25%3Bheight%3A100%25'%20src%3D'https%3A%2F%2Fcn1app%2Fstreams%2F1'%2F%3E%3Cscript%3Ewindow.cn1Media%20%3D%20document.getElementById('cn1Media')%3Bfunction%20callback(data)%7B%20cefQuery(%7Brequest%3A'shouldNavigate%3A'%2BJSON.stringify(data)%2C%20onSuccess%3A%20function(response)%7B%7D%2C%20onFailure%3Afunction(error_code%2C%20error_message)%20%7B%20console.log(error_message)%7D%7D)%3B%7Dcn1Media.addEventListener('pause'%2C%20function()%7B%20callback(%7B'state'%3A'paused'%7D)%7D)%3Bcn1Media.addEventListener('play'%2C%20function()%7B%20callback(%7B'state'%3A'playing'%7D)%7D)%3Bcn1Media.addEventListener('ended'%2C%20function()%7B%20callback(%7B'state'%3A'ended'%7D)%7D)%3Bcn1Media.addEventListener('durationchange'%2C%20function()%7B%20callback(%7B'duration'%3A%20Math.floor(cn1Media.duration%20*%201000)%7D)%7D)%3Bcn1Media.addEventListener('timeupdate'%2C%20function()%7B%20callback(%7B'time'%3A%20Math.floor(cn1Media.currentTime%20*%201000)%7D)%7D)%3Bcn1Media.addEventListener('volumechange'%2C%20function()%7B%20callback(%7B'volume'%3A%20Math.round(cn1Media.volume%20*%20100)%7D)%7D)%3Bcn1Media.addEventListener('error'%2C%20function()%7B%20var%20msg%20%3D%20'Unknown%20Error'%3B%20try%20%7Bmsg%20%3D%20cn1Media.error.message%20%2B%20'.%20Code%3D'%2Bcn1Media.error.code%3B%7Dcatch(e)%7B%7D%20callback(%7B'error'%3A%20msg%7D)%7D)%3B%3C%2Fscript%3E%20%3C%2Fbody%3E%3C%2Fhtml%3E (1)
debug:
BUILD SUCCESSFUL (total time: 35 seconds)
```

**Comment by shannah** [comment]
This is a different problem now.  I think this is likely an issue with trying to play a proprietary codec (e.g. h264).  Currently the CEF build we are using doesn't support h.264.

What type of video file are you trying to play?

**Comment by shannah** [comment]
I've added an issue for the proprietary codecs issue to track it.
https://github.com/codenameone/CodenameOne/issues/3200

**Comment by shannah** [comment]
Closing now - use #3200 to follow this.

**Comment by jsfan3** [comment]
Okay, thank you. I confirm that all my videos have h264 codecs.
